---
ID: "381eda26-5588-4df1-9b31-a9e48ba617da"
Parent: "aa11ba39-524e-4551-b7b0-ed88844439d5"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/exhibitor registration/Page/Section/Radio Button List/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180710T133515Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
