---
ID: "63163458-4108-433e-92f4-be85fd1f3edd"
Parent: "971c7d7a-ee2a-4205-8e76-0459b09874d7"
Template: "4c82b6dd-fe7c-4144-bcb3-f21b4080568f"
Path: /sitecore/content/Ineltec/Settings
DB: master
BranchID: "b2e4052a-6b3b-4527-933b-e24188c76b61"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/Setting.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160104T045042Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170323T054603Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
