---
ID: "4599b6f4-7cfe-4c4b-98b5-5133a52bc333"
Parent: "b86e1f8d-f7c8-409b-a3b2-83a6d3635ae4"
Template: "b86e1f8d-f7c8-409b-a3b2-83a6d3635ae4"
Path: "/sitecore/client/Applications/FormsBuilder/Components/Layouts/Renderings/Composites/PageDatasource/PageDatasource-Parameters/__Standard Values"
DB: core
SharedFields:
- ID: "c5217339-80d0-4725-9340-574eed8e9082"
  Hint: RenderingItemId
  Value: "{FC78F15A-4925-4FE6-990B-E7C8363F8689}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180424T121745Z
